language: node_js
node_js:
  - 6
sudo: false
dist: trusty
# services:
#   - postgresql
addons:
  postgresql: "9.6"
before_install:
  - psql -c 'create database test;' -U postgres
after_success:
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/test
    - NODE_ENV=TEST
